//! The words of the fun layer, in English, German, French, Spanish and Italian.
//!
//! Key, then the five languages in that order, exactly like [`super::TABLE`]:
//! the same tests hold both to a string in every language, the same holes in
//! each, and a length that fits. Nothing here is looked up any differently.

use super::Entry;

#[rustfmt::skip]
pub(super) const FUN: &[Entry] = &[
    // The settings page.
    ("tab.fun", ["Fun", "Spaß", "Folie", "Locura", "Follia"]),
    ("row.silliness", ["Silliness", "Albernheit", "Niveau de folie", "Nivel de locura", "Livello di follia"]),
    ("row.mount", ["Ride", "Reittier", "Monture", "Montura", "Cavalcatura"]),
    ("row.hat", ["Hat", "Hut", "Chapeau", "Sombrero", "Cappello"]),
    ("row.eyes", ["Googly eyes", "Wackelaugen", "Yeux mobiles", "Ojos saltones", "Occhi mobili"]),
    ("row.speed", ["Speed", "Tempo", "Vitesse", "Velocidad", "Velocità"]),
    ("row.wild", ["Track wildness", "Streckenwildheit", "Circuits déchaînés", "Circuitos salvajes", "Piste scatenate"]),
    ("row.neon", ["Neon", "Neon", "Néon", "Neón", "Neon"]),
    ("row.techno", ["Techno", "Techno", "Techno", "Techno", "Techno"]),
    ("row.chaos", ["Chaos events", "Chaos-Ereignisse", "Événements chaos", "Eventos de caos", "Eventi caos"]),
    ("fun.now", ["Silliness: {}", "Albernheit: {}", "Niveau de folie : {}", "Nivel de locura: {}", "Livello di follia: {}"]),
    ("fun.serious", ["Serious", "Ernst", "Sérieux", "Serio", "Serio"]),
    ("fun.silly", ["Silly", "Albern", "Rigolo", "Payaso", "Buffo"]),
    ("fun.bonkers", ["Bonkers", "Verrückt", "Dingue", "Loco", "Folle"]),
    ("mount.car", ["Car", "Auto", "Voiture", "Coche", "Auto"]),
    ("mount.chicken", ["Chicken", "Huhn", "Poulet", "Gallina", "Gallina"]),
    ("mount.duck", ["Rubber duck", "Quietscheente", "Canard en plastique", "Patito de goma", "Paperella di gomma"]),
    ("mount.tub", ["Bathtub", "Badewanne", "Baignoire", "Bañera", "Vasca da bagno"]),
    ("mount.cart", ["Shopping cart", "Einkaufswagen", "Chariot", "Carrito de compra", "Carrello"]),
    ("hat.surprise", ["Surprise me", "Überraschung", "Surprise", "Sorpresa", "Sorpresa"]),
    ("hat.bare", ["None", "Ohne", "Aucun", "Ninguno", "Nessuno"]),
    ("hat.party", ["Party hat", "Partyhut", "Chapeau de fête", "Gorro de fiesta", "Cappello da festa"]),
    ("hat.top", ["Top hat", "Zylinder", "Haut-de-forme", "Chistera", "Cilindro"]),
    ("hat.crown", ["Crown", "Krone", "Couronne", "Corona", "Corona"]),
    ("hat.cone", ["Traffic cone", "Pylon", "Cône", "Cono", "Cono"]),
    ("hat.propeller", ["Propeller cap", "Propellermütze", "Casquette à hélice", "Gorra con hélice", "Berretto con elica"]),
    ("hat.chef", ["Chef's hat", "Kochmütze", "Toque", "Gorro de chef", "Cappello da chef"]),
    ("hat.cowboy", ["Cowboy hat", "Cowboyhut", "Chapeau de cow-boy", "Sombrero vaquero", "Cappello da cowboy"]),
    ("speed.normal", ["Normal", "Normal", "Normale", "Normal", "Normale"]),
    ("speed.fast", ["Fast", "Schnell", "Rapide", "Rápido", "Veloce"]),
    ("speed.ludicrous", ["Ludicrous", "Absurd schnell", "Ridicule", "Ridículo", "Ridicola"]),
    ("speed.plaid", ["Plaid", "Plaid", "Plaid", "Plaid", "Plaid"]),
    ("wild.off", ["As surveyed", "Wie vermessen", "Comme mesuré", "Como medido", "Come rilevate"]),
    ("wild.rolling", ["Rolling hills", "Sanfte Hügel", "Collines douces", "Colinas suaves", "Colline dolci"]),
    ("wild.rollercoaster", ["Rollercoaster", "Achterbahn", "Montagnes russes", "Montaña rusa", "Montagne russe"]),
    ("wild.absurd", ["Absurd", "Absurd", "Absurde", "Absurdo", "Assurdo"]),
    ("hud.bonkers", ["BONKERS LAP  ·  FOR GLORY", "VERRÜCKTE RUNDE  ·  FÜR DEN RUHM", "TOUR DINGUE  ·  POUR LA GLOIRE", "VUELTA LOCA  ·  POR LA GLORIA", "GIRO FOLLE  ·  PER LA GLORIA"]),
    ("card.bonkers", ["BONKERS!", "VERRÜCKT!", "DINGUE !", "¡LOCURA!", "FOLLE!"]),
    ("card.bonkers_why", ["For glory only. Silly and Serious laps count.", "Nur für den Ruhm. Gezählt wird in Albern und Ernst.", "Pour la gloire. Rigolo et Sérieux comptent.", "Por la gloria. En Payaso y Serio sí cuentan.", "Per la gloria. Buffo e Serio contano."]),
    ("radio.techno", ["techno", "Techno", "techno", "techno", "techno"]),
    // The announcer and the score.
    ("score.label", ["FUN SCORE", "SPASS-PUNKTE", "POINTS DE FUN", "PUNTOS DE DIVERSIÓN", "PUNTI DIVERTIMENTO"]),
    ("pop.air", ["AIR", "LUFT", "AIR", "AIRE", "ARIA"]),
    ("pop.drift", ["DRIFT", "DRIFT", "DRIFT", "DRIFT", "DRIFT"]),
    ("say.airtime", ["AIR TIME!", "FLUGZEIT!", "EN L'AIR !", "¡A VOLAR!", "IN VOLO!"]),
    ("say.bigair", ["HUGE AIR!", "RIESENSPRUNG!", "SAUT GÉANT !", "¡SALTAZO!", "SALTONE!"]),
    ("say.combo", ["{}× COMBO!", "{}× KOMBO!", "COMBO ×{} !", "¡COMBO ×{}!", "COMBO ×{}!"]),
    ("say.highscore", ["NEW HIGH SCORE!", "NEUER HIGHSCORE!", "MEILLEUR SCORE !", "¡PUNTUACIÓN RÉCORD!", "NUOVO PUNTEGGIO RECORD!"]),
    ("rank.0", ["Nervous rookie", "Nervöser Anfänger", "Rookie nerveux", "Novato nervioso", "Novellino nervoso"]),
    ("rank.1", ["Mild menace", "Leichte Gefahr", "Petite menace", "Amenaza leve", "Minaccia lieve"]),
    ("rank.2", ["Certified chaos", "Zertifiziertes Chaos", "Chaos certifié", "Caos certificado", "Caos certificato"]),
    ("rank.3", ["Absolutely unhinged", "Völlig durchgeknallt", "Complètement déjanté", "Totalmente desquiciado", "Fuori di testa"]),
    ("rank.4", ["Feathered legend", "Gefiederte Legende", "Légende à plumes", "Leyenda emplumada", "Leggenda piumata"]),
    ("rank.5", ["Beyond bonkers", "Jenseits von verrückt", "Au-delà du dingue", "Más allá de la locura", "Oltre la follia"]),
    ("say.boost", ["BOOST!", "TURBO!", "TURBO !", "¡TURBO!", "TURBO!"]),
    ("say.jump", ["BOING!", "BOING!", "BOING !", "¡BOING!", "BOING!"]),
    ("pop.boost", ["BOOST", "TURBO", "TURBO", "TURBO", "TURBO"]),
    ("pop.jump", ["JUMP", "SPRUNG", "SAUT", "SALTO", "SALTO"]),
    ("pop.box", ["BOX", "KISTE", "BOÎTE", "CAJA", "SCATOLA"]),
    ("say.moo", ["MOO-VING VIOLATION!", "KUH-LISION!", "MEUH-URTRE !", "¡MUUUY MAL!", "MUUU-LTA!"]),
    ("say.strike", ["STRIKE!", "STRIKE!", "STRIKE !", "¡PLENO!", "STRIKE!"]),
    ("pop.cone", ["CONE", "PYLON", "CÔNE", "CONO", "CONO"]),
    ("pop.pin", ["PIN", "KEGEL", "QUILLE", "BOLO", "BIRILLO"]),
    ("pop.cow", ["COW", "KUH", "VACHE", "VACA", "MUCCA"]),
    ("pop.duck", ["DUCK", "ENTE", "CANARD", "PATO", "PAPERA"]),
    ("pop.melon", ["MELON", "MELONE", "PASTÈQUE", "SANDÍA", "ANGURIA"]),
    ("pop.crate", ["CRATE", "KISTE", "CAISSE", "CAJA", "CASSA"]),
    ("pop.balloon", ["POP", "PLOPP", "POP", "POP", "POP"]),
    ("pop.strike", ["STRIKE", "STRIKE", "STRIKE", "PLENO", "STRIKE"]),
    ("fx.moon", ["MOON GRAVITY!", "MONDSCHWERKRAFT!", "GRAVITÉ LUNAIRE !", "¡GRAVEDAD LUNAR!", "GRAVITÀ LUNARE!"]),
    ("fx.ice", ["ICE RINK!", "EISBAHN!", "PATINOIRE !", "¡PISTA DE HIELO!", "PISTA DI GHIACCIO!"]),
    ("fx.turbo", ["TURBO TIME!", "TURBO-ZEIT!", "HEURE DU TURBO !", "¡HORA DEL TURBO!", "ORA DEL TURBO!"]),
    ("fx.swapped", ["STEERING SWAPPED!", "LENKUNG VERTAUSCHT!", "DIRECTION INVERSÉE !", "¡DIRECCIÓN INVERTIDA!", "STERZO INVERTITO!"]),
    ("fx.giant", ["GIANT MODE!", "RIESEN-MODUS!", "MODE GÉANT !", "¡MODO GIGANTE!", "MODALITÀ GIGANTE!"]),
    ("fx.tiny", ["TINY MODE!", "MINI-MODUS!", "MODE MINUSCULE !", "¡MODO DIMINUTO!", "MODALITÀ MINI!"]),
    ("fx.cows", ["IT'S RAINING COWS!", "ES REGNET KÜHE!", "IL PLEUT DES VACHES !", "¡LLUEVEN VACAS!", "PIOVONO MUCCHE!"]),
    ("fx.roll", ["DO A BARREL ROLL!", "MACH EINE FASSROLLE!", "FAIS UN TONNEAU !", "¡HAZ UN BARREL ROLL!", "FAI UN BARREL ROLL!"]),
    ("fx.fisheye", ["FISHEYE!", "FISCHAUGE!", "FISHEYE !", "¡OJO DE PEZ!", "FISHEYE!"]),
    ("fx.disco", ["DISCO FEVER!", "DISCO-FIEBER!", "FIÈVRE DU DISCO !", "¡FIEBRE DISCO!", "DISCO FEVER!"]),
    ("fx.hyper", ["HYPERDRIVE!", "HYPERANTRIEB!", "HYPERVITESSE !", "¡HIPERIMPULSO!", "IPERSPAZIO!"]),
    ("fx.over", ["Back to normal. Boring.", "Wieder normal. Langweilig.", "Retour à la normale. Ennuyeux.", "Otra vez normal. Aburrido.", "Torna tutto normale. Noioso."]),
    ("pop.chaos", ["CHAOS", "CHAOS", "CHAOS", "CAOS", "CAOS"]),
    // The jokes. Translated for the laugh rather than the letter, so the wording
    // differs where the English pun does not carry over.
    ("quip.title.0", ["{} circuits. Zero dignity.", "{} Strecken. Null Würde.", "{} circuits. Zéro dignité.", "{} circuitos. Cero dignidad.", "{} circuiti. Zero dignità."]),
    ("quip.title.1", ["{} circuits, one chicken.", "{} Strecken, ein Huhn.", "{} circuits, un poulet.", "{} circuitos, una gallina.", "{} circuiti, una gallina."]),
    ("quip.title.2", ["Now with 400% more chicken.", "Jetzt mit 400 % mehr Huhn.", "Maintenant avec 400 % de poulet en plus.", "Ahora con un 400 % más de gallina.", "Ora con il 400% di gallina in più."]),
    ("quip.title.3", ["It's not a bug, it's a chicken.", "Das ist kein Bug, das ist ein Huhn.", "Ce n'est pas un bug, c'est un poulet.", "No es un bug, es una gallina.", "Non è un bug, è una gallina."]),
    ("quip.title.4", ["Hills were added. Nobody asked.", "Hügel wurden hinzugefügt. Keiner hat gefragt.", "Des collines ont été ajoutées. Personne n'a rien demandé.", "Se añadieron colinas. Nadie lo pidió.", "Sono state aggiunte delle colline. Nessuno le aveva chieste."]),
    ("quip.title.5", ["Please keep your wings inside the game.", "Bitte die Flügel im Spiel lassen.", "Veuillez garder vos ailes à l'intérieur du jeu.", "Por favor, mantén las alas dentro del juego.", "Si prega di tenere le ali all'interno del gioco."]),
    ("quip.title.6", ["{} circuits. Some of them are hills now.", "{} Strecken. Manche davon sind jetzt Hügel.", "{} circuits. Certains sont des collines, maintenant.", "{} circuitos. Algunos ya son colinas.", "{} circuiti. Alcuni ora sono colline."]),
    ("quip.title.7", ["Speed limit: yes.", "Tempolimit: ja.", "Limite de vitesse : oui.", "Límite de velocidad: sí.", "Limite di velocità: sì."]),
    ("quip.title.8", ["Cows on the road. You have been warned.", "Kühe auf der Straße. Du wurdest gewarnt.", "Des vaches sur la route. Vous êtes prévenu.", "Vacas en la carretera. Ya te avisamos.", "Mucche in strada. Sei stato avvisato."]),
    ("quip.title.9", ["I use Arch, btw. And a chicken.", "Ich benutze übrigens Arch. Und ein Huhn.", "Je suis sous Arch, au fait. Et un poulet.", "Uso Arch, por cierto. Y una gallina.", "Uso Arch, tra l'altro. E una gallina."]),
    ("quip.title.10", ["Made with love and one (1) rooster.", "Mit Liebe gemacht und einem (1) Hahn.", "Fait avec amour et un (1) coq.", "Hecho con cariño y un (1) gallo.", "Fatto con amore e un (1) gallo."]),
    ("quip.title.11", ["Do not feed the tube-men.", "Bitte die Schlauchmänner nicht füttern.", "Ne pas nourrir les bonshommes gonflables.", "No alimentes a los muñecos hinchables.", "Non nutrire gli omini gonfiabili."]),
    ("quip.title.12", ["Warning: contains techno.", "Achtung: enthält Techno.", "Attention : contient de la techno.", "Aviso: contiene techno.", "Attenzione: contiene techno."]),
    ("quip.title.13", ["Serious mode is in Settings. If you must.", "Der Ernst-Modus steckt in den Einstellungen. Wenn es sein muss.", "Le mode sérieux est dans les Réglages. Si vous y tenez.", "El modo serio está en Ajustes. Si te empeñas.", "La modalità seria è nelle Impostazioni. Se proprio devi."]),
    ("quip.pause.0", ["Take a breather. The cows can wait.", "Verschnauf mal. Die Kühe warten.", "Reprenez votre souffle. Les vaches peuvent attendre.", "Tómate un respiro. Las vacas pueden esperar.", "Prenditi una pausa. Le mucche possono aspettare."]),
    ("quip.pause.1", ["Paused. The chicken is judging you.", "Pause. Das Huhn beurteilt dich.", "En pause. Le poulet vous juge.", "Pausa. La gallina te está juzgando.", "In pausa. La gallina ti sta giudicando."]),
    ("quip.pause.2", ["Have a snack. The ducks will hold your place.", "Gönn dir einen Snack. Die Enten halten deinen Platz.", "Prenez un en-cas. Les canards gardent votre place.", "Come algo. Los patos te guardan el sitio.", "Fatti uno spuntino. Le papere ti tengono il posto."]),
    ("quip.pause.3", ["Time out! No cows were harmed. Yet.", "Auszeit! Keine Kuh kam zu Schaden. Bisher.", "Temps mort ! Aucune vache n'a été blessée. Pour l'instant.", "¡Tiempo muerto! Ninguna vaca ha sufrido daños. Todavía.", "Time out! Nessuna mucca è stata maltrattata. Per ora."]),
    ("quip.pause.4", ["Paused. The techno waits for no one.", "Pause. Techno wartet auf niemanden.", "En pause. La techno n'attend personne.", "Pausa. El techno no espera a nadie.", "In pausa. La techno non aspetta nessuno."]),
    ("quip.pause.5", ["The tube-men are still waving, though.", "Die Schlauchmänner winken trotzdem weiter.", "Les bonshommes gonflables, eux, continuent de saluer.", "Los muñecos hinchables siguen saludando, eso sí.", "Gli omini gonfiabili, però, continuano a salutare."]),
    ("quip.pause.6", ["Deep breath. Wings out. Ready?", "Tief durchatmen. Flügel raus. Bereit?", "Inspirez. Ailes déployées. Prêt ?", "Respira hondo. Alas fuera. ¿Listo?", "Respiro profondo. Ali aperte. Pronto?"]),
    ("quip.pause.7", ["Halt! Who goes there? Oh, it's you.", "Halt! Wer da? Ach, du bist es.", "Halte ! Qui va là ? Ah, c'est vous.", "¡Alto! ¿Quién va? Ah, eres tú.", "Alt! Chi va là? Ah, sei tu."]),
    ("quip.pause.8", ["sudo pause", "sudo pause", "sudo pause", "sudo pause", "sudo pause"]),
    ("quip.pause.9", ["Loading more chaos. Please stand by.", "Mehr Chaos wird geladen. Bitte warten.", "Chargement de chaos supplémentaire. Veuillez patienter.", "Cargando más caos. Espera un momento.", "Sto caricando altro caos. Attendere prego."]),
    ("quip.load.0", ["Teaching the chicken to run…", "Dem Huhn das Rennen beibringen…", "On apprend au poulet à courir…", "Enseñando a correr a la gallina…", "Insegno alla gallina a correre…"]),
    ("quip.load.1", ["Inflating the tube-men…", "Schlauchmänner werden aufgeblasen…", "Gonflage des bonshommes gonflables…", "Inflando a los muñecos hinchables…", "Gonfio gli omini gonfiabili…"]),
    ("quip.load.2", ["Hiding cows on the racetrack…", "Kühe auf der Rennstrecke verstecken…", "On cache des vaches sur la piste…", "Escondiendo vacas en el circuito…", "Nascondo le mucche in pista…"]),
    ("quip.load.3", ["Polishing the googly eyes…", "Wackelaugen werden poliert…", "Polissage des yeux mobiles…", "Puliendo los ojos saltones…", "Lucido gli occhioni…"]),
    ("quip.load.4", ["Adding hills. Lots of hills.", "Hügel werden hinzugefügt. Viele Hügel.", "Ajout de collines. Beaucoup de collines.", "Añadiendo colinas. Muchas colinas.", "Aggiungo colline. Un sacco di colline."]),
    ("quip.load.5", ["Tuning the techno…", "Der Techno wird gestimmt…", "Accordage de la techno…", "Afinando el techno…", "Accordo la techno…"]),
    ("quip.load.6", ["Herding the ducks…", "Enten werden zusammengetrieben…", "On rassemble les canards…", "Pastoreando a los patos…", "Raduno le papere…"]),
    ("quip.load.7", ["Reticulating splines…", "Reticulating splines…", "Reticulating splines…", "Reticulating splines…", "Reticulating splines…"]),
    ("quip.load.8", ["Compiling shaders. This is fine.", "Shader werden kompiliert. Alles in Ordnung.", "Compilation des shaders. Tout va bien.", "Compilando shaders. Todo bien.", "Compilo gli shader. Va tutto bene."]),
    ("quip.load.9", ["Arranging the bowling pins…", "Kegel werden aufgestellt…", "On aligne les quilles…", "Colocando los bolos…", "Sistemo i birilli…"]),
    ("quip.load.10", ["Charging the boost pads…", "Turbo-Felder werden aufgeladen…", "Recharge des plaques de turbo…", "Cargando las placas de turbo…", "Carico le piastre turbo…"]),
    ("quip.load.11", ["Convincing the balloons to float…", "Luftballons werden überredet zu schweben…", "On convainc les ballons de flotter…", "Convenciendo a los globos de que floten…", "Convinco i palloncini a fluttuare…"]),
    ("quip.load.12", ["Feeding the rooster…", "Der Hahn wird gefüttert…", "On donne à manger au coq…", "Dando de comer al gallo…", "Do da mangiare al gallo…"]),
    ("quip.load.13", ["Sharpening the lasers…", "Laser werden geschärft…", "On aiguise les lasers…", "Afilando los láseres…", "Affilo i laser…"]),
    ("quip.load.14", ["Consulting the cows…", "Die Kühe werden befragt…", "On consulte les vaches…", "Consultando a las vacas…", "Consulto le mucche…"]),
    ("quip.load.15", ["Removing the brakes… just kidding.", "Bremsen werden ausgebaut… War ein Scherz.", "Retrait des freins… je plaisante.", "Quitando los frenos… es broma.", "Rimuovo i freni… scherzavo."]),
    ("hud.edition_bonkers", ["TODORA  /  BONKERS EDITION", "TODORA  /  VERRÜCKTE EDITION", "TODORA  /  ÉDITION DINGUE", "TODORA  /  EDICIÓN LOCA", "TODORA  /  EDIZIONE FOLLE"]),
    ("hud.edition_silly", ["TODORA  /  SILLY MODE", "TODORA  /  ALBERNER MODUS", "TODORA  /  MODE RIGOLO", "TODORA  /  MODO PAYASO", "TODORA  /  MODALITÀ BUFFA"]),
    ("title.sticker", ["BONKERS EDITION!", "VERRÜCKTE EDITION!", "ÉDITION DINGUE !", "¡EDICIÓN LOCA!", "EDIZIONE FOLLE!"]),
    ("hud.fun_keys", ["H  Honk    E  Hop", "H  Hupe    E  Hopser", "H  Klaxon    E  Saut", "H  Claxon    E  Salto", "H  Clacson    E  Saltello"]),
    ("hud.fun_keys_silly", ["H  Honk", "H  Hupe", "H  Klaxon", "H  Claxon", "H  Clacson"]),
    // The controls.
    ("act.horn", ["Horn", "Hupe", "Klaxon", "Claxon", "Clacson"]),
    ("act.hop", ["Hop", "Hopser", "Saut", "Salto", "Saltello"]),
];

/// Silly achievements: id, name and what each asks for.
#[rustfmt::skip]
pub(super) const ACHIEVEMENTS: &[(&str, [&str; 5], [&str; 5])] = &[
    ("fun-honk-25", ["Honk if you're happy", "Hupe, wenn du glücklich bist", "Klaxonnez si vous êtes heureux", "Toca el claxon si eres feliz", "Suona se sei felice"], ["Honk 25 times", "Hupe 25-mal", "Klaxonnez 25 fois", "Toca el claxon 25 veces", "Suona il clacson 25 volte"]),
    ("fun-honk-250", ["Public nuisance", "Ruhestörung", "Nuisance publique", "Molestia pública", "Disturbo della quiete"], ["Honk 250 times", "Hupe 250-mal", "Klaxonnez 250 fois", "Toca el claxon 250 veces", "Suona il clacson 250 volte"]),
    ("fun-crow", ["Cock-a-doodle-doo", "Kikeriki", "Cocorico", "Quiquiriquí", "Chicchirichì"], ["Hear the rooster crow", "Hör den Hahn krähen", "Entendez le coq chanter", "Oye cantar al gallo", "Senti il gallo cantare"]),
    ("fun-cow-1", ["Moo-ving violation", "Kuh-lision", "Meuh-urtre", "Muuuy mal", "Muuu-lta"], ["Hit a cow", "Fahr eine Kuh an", "Renversez une vache", "Atropella una vaca", "Investi una mucca"]),
    ("fun-cow-25", ["Beef with the law", "Rinderwahnsinn", "Vache folle", "Vacas locas", "Mucca pazza"], ["Hit 25 cows", "Fahr 25 Kühe an", "Renversez 25 vaches", "Atropella 25 vacas", "Investi 25 mucche"]),
    ("fun-strike", ["Strike!", "Strike!", "Strike !", "¡Pleno!", "Strike!"], ["Knock down all ten pins in one go", "Wirf alle zehn Kegel auf einmal um", "Renversez les dix quilles d'un coup", "Derriba los diez bolos de una vez", "Abbatti tutti e dieci i birilli in un colpo"]),
    ("fun-air-60", ["Frequent flyer", "Vielflieger", "Voyageur fréquent", "Viajero frecuente", "Viaggiatore frequente"], ["Spend a minute in the air", "Verbringe eine Minute in der Luft", "Passez une minute en l'air", "Pasa un minuto en el aire", "Trascorri un minuto in aria"]),
    ("fun-air-600", ["Wright brothers", "Gebrüder Wright", "Frères Wright", "Hermanos Wright", "Fratelli Wright"], ["Spend ten minutes in the air", "Verbringe zehn Minuten in der Luft", "Passez dix minutes en l'air", "Pasa diez minutos en el aire", "Trascorri dieci minuti in aria"]),
    ("fun-combo", ["Combo breaker", "Kombo-Brecher", "Briseur de combos", "Rompecombos", "Spacca-combo"], ["Reach an 8× combo", "Erreiche eine 8×-Kombo", "Atteignez un combo ×8", "Alcanza un combo ×8", "Raggiungi un combo ×8"]),
    ("fun-score-10k", ["Certified chaos", "Zertifiziertes Chaos", "Chaos certifié", "Caos certificado", "Caos certificato"], ["Score 10,000 fun points in one lap", "Erziele 10.000 Spaßpunkte in einer Runde", "Marquez 10\u{00A0}000 points de fun en un tour", "Consigue 10\u{00A0}000 puntos de diversión en una vuelta", "Ottieni 10.000 punti divertimento in un giro"]),
    ("fun-score-50k", ["Beyond bonkers", "Jenseits von verrückt", "Au-delà du dingue", "Más allá de la locura", "Oltre la follia"], ["Score 50,000 fun points in one lap", "Erziele 50.000 Spaßpunkte in einer Runde", "Marquez 50\u{00A0}000 points de fun en un tour", "Consigue 50\u{00A0}000 puntos de diversión en una vuelta", "Ottieni 50.000 punti divertimento in un giro"]),
    ("fun-chaos-10", ["Chaos theory", "Chaostheorie", "Théorie du chaos", "Teoría del caos", "Teoria del caos"], ["Get through ten chaos events", "Überstehe zehn Chaos-Ereignisse", "Traversez dix événements chaos", "Supera diez eventos de caos", "Supera dieci eventi caos"]),
    ("fun-balloons-50", ["Party pooper", "Spielverderber", "Rabat-joie", "Aguafiestas", "Guastafeste"], ["Pop 50 balloons", "Lass 50 Luftballons platzen", "Éclatez 50 ballons", "Explota 50 globos", "Fai scoppiare 50 palloncini"]),
    ("fun-boxes-20", ["Mystery solved", "Rätsel gelöst", "Mystère résolu", "Misterio resuelto", "Mistero risolto"], ["Open 20 mystery boxes", "Öffne 20 Rätselkisten", "Ouvrez 20 boîtes mystère", "Abre 20 cajas misteriosas", "Apri 20 scatole misteriose"]),
    ("fun-mounts", ["Anything with wheels", "Alles, was Räder hat", "Tout ce qui roule", "Todo lo que tenga ruedas", "Tutto ciò che ha ruote"], ["Finish a lap on every ride", "Beende auf jedem Reittier eine Runde", "Terminez un tour sur chaque monture", "Termina una vuelta con cada montura", "Completa un giro con ogni cavalcatura"]),
];
