//! Lime Rock Park.
//!
//! Generated by `tools/make_track.py docs/track-screening/traces/lime-rock.geojson lime_rock "Connecticut Valley"`.
//! GPS from tobi/track-atlas (OpenStreetMap contributors; ODbL 1.0) `c783def5a24d`, id `docs/track-screening/traces/lime-rock.geojson`
//! (2.367 km). Heights from the Open-Meteo DEM, sampled at those same fixes.
//! Turned to begin at the start/finish line, 41.9285, -73.38069.

use super::Circuit;

pub(super) const CIRCUIT: Circuit = Circuit {
    id: "lime-rock",
    name: "Connecticut Valley",
    // Keep the surveyed plan unless the geometry and driving checks require it.
    corners: 1.0,
    // What one lap comes out as once the circuit has been shrunk and had its
    // corners opened. Run `cargo test --locked --lib the_menu_shows_the_lap`
    // and write down the figure it asks for.
    lap: 277.0,
    // The shared plan scale. Raise it only if the circuit cannot carry a road
    // and a shoulder at 1, and only as far as it has to be raised: see
    // `Circuit::plan_scale` for what a multiplier gives up.
    plan_scale: 1.0,
    centreline: CENTRELINE,
    // Where the circuit passes over itself. Almost none do; see `Crossing`, and
    // `screen_tracks.py`, whose `finished_crossings` column is what says
    // whether this one needs a line here.
    crossings: &[],
};

/// Metres from the circuit centroid. Y is height above the lowest point.
/// Connect the last sample back to the first to close the lap.
const CENTRELINE: &[[f32; 3]] = &[
    [196.81, 2.00, -164.19],
    [270.32, 1.00, -131.06],
    [298.72, 1.00, -116.77],
    [319.30, 1.00, -109.08],
    [380.19, 1.00, -81.28],
    [389.14, 1.00, -76.85],
    [396.32, 4.00, -71.44],
    [404.45, 4.00, -62.65],
    [412.16, 1.00, -50.96],
    [418.83, 1.00, -36.40],
    [422.07, 1.00, -24.83],
    [423.02, 1.00, -9.89],
    [422.59, 1.00, 0.12],
    [418.87, 1.00, 14.66],
    [413.18, 1.00, 27.47],
    [404.97, 0.00, 41.20],
    [397.64, 0.00, 50.72],
    [392.27, 0.00, 56.65],
    [383.80, 0.00, 63.66],
    [375.88, 0.00, 67.89],
    [363.66, 0.00, 72.26],
    [355.79, 0.00, 73.59],
    [345.82, 0.00, 73.68],
    [336.88, 0.00, 72.71],
    [331.10, 0.00, 71.16],
    [314.01, 1.00, 62.91],
    [247.07, 1.00, 21.08],
    [223.30, 1.00, 8.31],
    [214.08, 1.00, 4.47],
    [202.47, 1.00, 1.60],
    [190.52, 1.00, 1.28],
    [177.70, 2.00, 3.20],
    [162.58, 2.00, 8.35],
    [152.82, 2.00, 13.38],
    [140.46, 2.00, 23.51],
    [134.13, 2.00, 31.23],
    [129.58, 1.00, 41.24],
    [126.75, 1.00, 52.91],
    [125.80, 1.00, 69.92],
    [126.55, 1.00, 89.94],
    [128.39, 1.00, 108.90],
    [128.69, 1.00, 125.92],
    [124.92, 2.00, 141.47],
    [116.29, 2.00, 156.08],
    [110.57, 8.00, 161.68],
    [101.93, 8.00, 168.49],
    [82.65, 8.00, 178.99],
    [44.62, 13.00, 194.20],
    [18.28, 13.00, 203.55],
    [5.81, 13.00, 207.16],
    [-13.69, 13.00, 211.43],
    [-42.62, 13.00, 211.54],
    [-94.97, 13.00, 203.85],
    [-123.83, 13.00, 201.59],
    [-144.78, 13.00, 202.09],
    [-166.69, 12.00, 203.73],
    [-253.99, 11.00, 213.57],
    [-259.94, 11.00, 213.05],
    [-264.48, 11.00, 211.04],
    [-267.37, 11.00, 208.28],
    [-270.36, 11.00, 203.10],
    [-273.26, 11.00, 187.35],
    [-275.77, 11.00, 181.97],
    [-281.43, 11.00, 177.98],
    [-305.09, 15.00, 170.03],
    [-312.65, 15.00, 165.29],
    [-318.58, 15.00, 156.04],
    [-333.03, 16.00, 127.43],
    [-343.89, 16.00, 108.28],
    [-353.25, 16.00, 96.57],
    [-374.46, 17.00, 73.94],
    [-392.40, 17.00, 56.64],
    [-411.54, 16.00, 21.48],
    [-449.41, 19.00, -55.87],
    [-455.62, 19.00, -69.55],
    [-461.81, 19.00, -88.57],
    [-461.72, 19.00, -99.55],
    [-459.37, 19.00, -114.40],
    [-453.25, 19.00, -133.45],
    [-443.72, 23.00, -149.87],
    [-435.98, 23.00, -160.32],
    [-426.56, 23.00, -170.67],
    [-332.56, 13.00, -270.38],
    [-312.56, 13.00, -289.98],
    [-299.14, 13.00, -301.98],
    [-280.25, 7.00, -316.77],
    [-261.69, 7.00, -328.54],
    [-247.55, 7.00, -333.46],
    [-229.91, 7.00, -336.85],
    [-215.98, 4.00, -337.91],
    [-194.07, 4.00, -336.70],
    [-177.70, 4.00, -332.27],
    [-159.96, 3.00, -325.55],
    [-80.75, 5.00, -289.77],
    [-67.06, 5.00, -281.55],
    [-16.24, 5.00, -258.15],
    [-2.87, 5.00, -254.32],
];
