#!/usr/bin/env python3
"""Bake flag-icons into Todora's atlas. Requires cairosvg and Pillow.
Usage: python3 tools/make_flags.py /path/to/flag-icons
Only ISO countries are selectable; no network calls at game runtime.
"""
import io
import json
from pathlib import Path
import subprocess
import sys
import cairosvg
from PIL import Image

source = Path(sys.argv[1])
root = Path(__file__).resolve().parents[1]
countries = sorted((c for c in json.loads((source / 'country.json').read_text()) if c.get('iso')), key=lambda c: c['name'])
assert len(countries) == 249
atlas = Image.new('RGBA', (16 * 64, 16 * 48))
for i, country in enumerate(countries):
    png = cairosvg.svg2png(url=str(source / country['flag_4x3']), output_width=64, output_height=48)
    atlas.paste(Image.open(io.BytesIO(png)), ((i % 16) * 64, (i // 16) * 48))
folder = root / 'assets/ui/flags'
folder.mkdir(parents=True, exist_ok=True)
atlas.save(folder / 'countries.png', optimize=True)
(folder / 'LICENSE').write_bytes((source / 'LICENSE').read_bytes())
revision = subprocess.check_output(['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip()
(folder / 'CREDITS.md').write_text(f'# Country flags\n\n[flag-icons](https://github.com/lipis/flag-icons) by Lipis and contributors, MIT.\nPinned revision: `{revision}`.\n\n249 ISO countries, rendered at 64×48 in a 16-column atlas.\nRegenerate with `tools/make_flags.py` using that source checkout, CairoSVG and Pillow.\nCountry names follow the source catalogue; flags represent the player’s chosen country.\n')
lines = ['//! ISO countries in flag-atlas order; generated by tools/make_flags.py.', 'pub(crate) const ALL: &[(&str, &str)] = &[']
for c in countries:
    lines.append(f'    ("{c["code"].upper()}", {json.dumps(c["name"], ensure_ascii=False)}),')
lines += ['];', '', 'pub(crate) fn name(code: &str) -> &str {', '    ALL.iter().find(|(id, _)| *id == code).map_or(code, |(_, name)| *name)', '}', '']
(root / 'src/identity/countries.rs').write_text('\n'.join(lines))
print(f'Baked {len(countries)} flags from {revision}')
