#!/usr/bin/env python3
"""Turn a real circuit into a Todora centreline module.

    tools/make_track.py at-1969 red_bull_ring "Red Bull Ring"
    tools/make_track.py be-1925 spa_francorchamps "Spa-Francorchamps"

The plan comes from bacinger/f1-circuits, which traces circuit centrelines as
GeoJSON in WGS84; the heights come from the Open-Meteo DEM, sampled at those
same fixes. Both are public and both are what the existing circuits were built
from. Re-running this on an id already in the game reproduces its trace to
within a centimetre — the Red Bull Ring was projected by hand before this
existed, and a centimetre of a real circuit is a millimetre of a Todora lap.

The trace is projected flat about its own centroid — equirectangular on the
WGS84 equatorial radius, which is good to a few centimetres over a circuit —
and written out in metres, north as -Z so the map reads the way Bevy's axes do.
Heights are whole metres above the lowest point on the lap; the DEM is quantised
to the metre anyway, and `ribbon` smooths and grade-caps what it is given.

Nothing here scales anything: `src/track/mod.rs` decides how much of a real
circuit a Todora lap is, and it decides it the same way for every circuit.
"""

import json
import math
import re
import subprocess
import sys
import urllib.parse
import urllib.request
from pathlib import Path

TRACE = "https://raw.githubusercontent.com/bacinger/f1-circuits/master/circuits/{}.geojson"
DEM = "https://api.open-meteo.com/v1/elevation"
# WGS84 equatorial radius. The flattening does not survive the rounding to
# centimetres over a few kilometres, so the sphere is enough.
RADIUS = 6378137.0
# Open-Meteo takes this many coordinates per request.
BATCH = 100
CIRCUITS = Path(__file__).resolve().parent.parent / "src" / "track" / "circuits"


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as response:
        return json.load(response)


def trace(circuit_id):
    """The circuit's GPS fixes, open: the closing duplicate is dropped."""
    data = fetch(TRACE.format(circuit_id))
    feature = data["features"][0]
    fixes = feature["geometry"]["coordinates"]
    if fixes[0] == fixes[-1]:
        fixes = fixes[:-1]
    return feature["properties"], fixes


def plan(fixes):
    """Metres east and south of the centroid of the trace."""
    lon0 = sum(lon for lon, _ in fixes) / len(fixes)
    lat0 = sum(lat for _, lat in fixes) / len(fixes)
    scale = math.radians(RADIUS)
    return [
        ((lon - lon0) * scale * math.cos(math.radians(lat0)), -(lat - lat0) * scale)
        for lon, lat in fixes
    ]


def heights(fixes):
    """Whole metres above the lowest fix, from the DEM."""
    sampled = []
    for start in range(0, len(fixes), BATCH):
        batch = fixes[start : start + BATCH]
        query = urllib.parse.urlencode(
            {
                "latitude": ",".join(f"{lat:.6f}" for _, lat in batch),
                "longitude": ",".join(f"{lon:.6f}" for lon, _ in batch),
            }
        )
        sampled += fetch(f"{DEM}?{query}")["elevation"]
    lowest = min(sampled)
    return [round(metres - lowest) for metres in sampled]


def lap_length(points):
    return sum(math.dist(points[i], points[(i + 1) % len(points)]) for i in range(len(points)))


def module(circuit_id, module_name, name, properties, points, ys):
    slug = module_name.replace("_", "-")
    km = lap_length(points) / 1000.0
    rows = "".join(
        f"    [{x:.2f}, {y:.2f}, {z:.2f}],\n" for (x, z), y in zip(points, ys)
    )
    title = properties.get("Name", name)
    where = properties.get("Location", "")
    if where and where.split()[0].lower() not in title.lower():
        title = f"{title}, {where}"
    return f"""//! {title}.
//!
//! Generated by `tools/make_track.py {circuit_id} {module_name} "{name}"`.
//! GPS from bacinger/f1-circuits ({km:.3f} km). Heights from the Open-Meteo DEM.

use super::Circuit;

pub(super) const CIRCUIT: Circuit = Circuit {{
    id: "{slug}",
    name: "{name}",
    // The trace as surveyed. Turn this up until `corners_are_corners` is happy
    // and `every_circuit_carries_a_road` is not yet unhappy: the road is five
    // times too wide for the shrunk land, so a corner needs exaggerating before
    // it is a corner, and a circuit wound tightly on itself has less room to do
    // it in than one made of straights.
    corners: 1.0,
    centreline: CENTRELINE,
}};

/// Metres from the circuit centroid. Y is height above the lowest point.
/// Connect the last sample back to the first to close the lap.
const CENTRELINE: &[[f32; 3]] = &[
{rows}];
"""


def register(module_name):
    """Add the new circuit to `circuits/mod.rs`, if it is not already there."""
    path = CIRCUITS / "mod.rs"
    source = path.read_text()
    if re.search(rf"^mod {module_name};$", source, re.M):
        return
    mods = sorted(re.findall(r"^mod (\w+);$", source, re.M) + [module_name])
    source = re.sub(
        r"^mod \w+;(\n^mod \w+;)*$",
        "\n".join(f"mod {m};" for m in mods),
        source,
        count=1,
        flags=re.M,
    )
    listed = re.search(r"const ALL: &\[Circuit\] = &\[(.*?)\];", source, re.S)
    entries = [e.strip() for e in listed.group(1).split(",") if e.strip()]
    entries.append(f"{module_name}::CIRCUIT")
    source = source[: listed.start()] + (
        "const ALL: &[Circuit] = &[\n"
        + "".join(f"    {e},\n" for e in entries)
        + "];"
    ) + source[listed.end() :]
    path.write_text(source)


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    circuit_id, module_name, name = sys.argv[1:]
    properties, fixes = trace(circuit_id)
    points = plan(fixes)
    path = CIRCUITS / f"{module_name}.rs"
    path.write_text(module(circuit_id, module_name, name, properties, points, heights(fixes)))
    register(module_name)
    subprocess.run(["cargo", "fmt", "--all"], cwd=CIRCUITS.parents[2], check=False)
    print(f"{path}: {len(fixes)} fixes, {lap_length(points) / 1000.0:.3f} km")


if __name__ == "__main__":
    main()
